### ISSUE TITLE
Reading data: The file “GoogleService-Info.plist” couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by GanZhiXiong** [santetis/flutter_camera_ml_vision#105]
Flutter version: Flutter 1.12.13+hotfix.6-pre.1 • channel stable •
iOS version: iOS13.3.1

xcode build error:
`
 Showing Recent Messages /Users/ganzhixiong/Downloads/flutter_camera_ml_vision-master (2).zip Folder/flutter_camera_ml_vision-master/example/ios/Runner/GoogleService-Info.plist:0: Reading data: The file “GoogleService-Info.plist” couldn’t be opened because there is no such file.
`

**Comment by jaumard** [comment]
if you didn't follow the setup of firebase it's normal to have this, it's not related to this package. check https://codelabs.developers.google.com/codelabs/flutter-firebase/#6
