### ISSUE TITLE
ameraException(CameraAccess, Illegal state encountered in camera service.)

### ISSUE THREAD

**Issue by kw2019ltd** [santetis/flutter_camera_ml_vision#115]
hi getting below

```
Non-fatal Exception: java.lang.Exception: CameraException(CameraAccess, Illegal state encountered in camera service.)
       at CameraController.startImageStream(camera.dart:405)
```

![image](https://user-images.githubusercontent.com/47334522/82839318-a284f080-9ed7-11ea-98fb-3400a29917f1.png)

**Comment by jaumard** [comment]
Look like a camera bug, please try last version we update it, if it's the same please open an issue there
