### ISSUE TITLE
cannot read Aztek barcode

### ISSUE THREAD

**Issue by piotr-swinarski** [santetis/flutter_camera_ml_vision#119]
Hi Team,

can you read attached Aztec barcode using solution?

![barcode](https://user-images.githubusercontent.com/13232539/85283981-9cf6d800-b48e-11ea-99a3-89b80ad0b903.gif)

I have errors like this:
![Screenshot_2020-06-22-13-46-19-081_info swinarski aztec2](https://user-images.githubusercontent.com/13232539/85284472-8d2bc380-b48f-11ea-8c30-0366696bfd4f.png)

BR,
Peter

**Comment by kevin-sakemaer** [comment]
sorry for the delay you can specify the format of your barcode in the BarcodeDetectorOptions.
By specifying Aztec i can read it.
