### ISSUE TITLE
Your Flutter application is created using an older version of the Android embedding. It's being deprecated in favor of Android embedding v2

### ISSUE THREAD

**Issue by kw2019ltd** [santetis/flutter_camera_ml_vision#124]
hi the plugin needs to work with Android embedding v2

Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.

**Comment by jaumard** [comment]
We're not using native code on this plugin, so this issue should be on the right plugin with should be camera or ml_vision, once they are in v2 we will update deps.

**Comment by kw2019ltd** [comment]
Yes sorry you can close the issue.
