### ISSUE TITLE
Deprecated device_info version

### ISSUE THREAD

**Issue by ndasim** [santetis/flutter_camera_ml_vision#126]
I upgraded device_info plugin version to 1.0.0 and flutter_camera_ml_vision started to give version solving error

> flutter_camera_ml_vision 2.2.5 depends on device_info ^0.4.1+4 and app depends on device_info 1.0.0, flutter_camera_ml_vision 2.2.5 is forbidden.

https://pub.dev/packages/device_info

**Comment by ndasim** [comment]
Sorry for opening issue, I realized my flutter_camera_ml_vision package is not up to date. I updated it to 2.3.0 and it solved.

I'm closing issue.

**Comment by ndasim** [comment]
Sorry for my silliness, even I upgraded the flutter_camera_ml_vision version to 2.3.0 it continued. Please upgrade the device_info plugin

**Comment by jaumard** [comment]
Should be ok now :)
