### ISSUE TITLE
boundingBox transformation

### ISSUE THREAD

**Issue by saddy001** [santetis/flutter_camera_ml_vision#13]
Hey, at first thanks for this useful package. 
Currently I'm drawing bounding boxes around text in the live preview (examples/main_live.dart) with CustomPainter. However, when using the ocrElement.boundingBox left, top, right and bottom properties, the box appears displaced and not directly around the recognized words. 
So I guess the coordinates must be scaled or shifted somehow.

For top and bottom, there seems to be a constant scaling factor that fixes the issue (e.g. ocrElement.boundingBox.top * 0.96). For left and right, this is not the case: If the detected text is on the left hand side of the image, the box appears too far right and if it's on the right hand side, the box is too far left.

I had a look at the new ScannerOverlayShape in example/main.dart, but there is much scaling going on. Could you explain how the X and Y coordinates must be transformed to display the boxes at the right location?

**Comment by jaumard** [comment]
Hey @saddy001 did you check https://github.com/bparrishMines/mlkit_demo ? it does draw boxes on detected text already, might help you :)

**Comment by saddy001** [comment]
Yes, they use the following scaling:
```
final double scaleX = widgetSize.width / imageSize.width;
final double scaleY = widgetSize.height / imageSize.height;

return Rect.fromLTRB(
    rect.left.toDouble() * scaleX,
    rect.top.toDouble() * scaleY,
    rect.right.toDouble() * scaleX,
    rect.bottom.toDouble() * scaleY,
);
```
I also tried to scale it this way, with the _widgetSize_ being the _size_ parameter of the paint(Canvas canvas, Size size) function in CustomPainter, and imageSize being the CameraMlVision.size.width and height attributes. The bbox is still displaced. Here is the result:

a  |  b
:-------------------------:|:-------------------------:
![Screenshot_20190424-175428](https://user-images.githubusercontent.com/13658554/56674955-4b509300-66bb-11e9-9b2a-3769c0320add.jpg) | ![Screenshot_20190424-175250](https://user-images.githubusercontent.com/13658554/56674956-4b509300-66bb-11e9-9e88-682861a817bc.jpg)
:-------------------------:|:-------------------------:
![Screenshot_20190424-175230](https://user-images.githubusercontent.com/13658554/56674958-4be92980-66bb-11e9-9c97-08d914526011.jpg) | ![Screenshot_20190424-175205](https://user-images.githubusercontent.com/13658554/56674960-4be92980-66bb-11e9-9c84-f7c3b20f93dd.jpg)
:-------------------------:|:-------------------------:
![Screenshot_20190424-175043](https://user-images.githubusercontent.com/13658554/56674961-4be92980-66bb-11e9-8ac5-af28ddb38cf9.jpg)

**Comment by saddy001** [comment]
I got it. I was using CameraMlVision.size, where I should have used _cameraController.value.previewSize. 

However, the CameraMlVisionState._cameraController property is private in flutter_camera_ml_vision.dart. Could you please find a way to make it accessible from outside packages or at least define a get-method for previewSize?

**Comment by Kleak** [comment]
from where are you getting `widgetSize` ?

**Comment by saddy001** [comment]
WidgetSize is the size parameter of the paint(Canvas canvas, Size size) function in my CustomPainter.

**Comment by saddy001** [comment]
Thanks!
