### ISSUE TITLE
issue only on Android about FirebaseVisionImageMetadata 

### ISSUE THREAD

**Issue by kenpz** [santetis/flutter_camera_ml_vision#131]
[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/ml/vision/common/FirebaseVisionImageMetadata$Builder;

java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.ml.vision.common.FirebaseVisionImageMetadata$Builder" on path: DexPathList[[zip file "/data/app/com.sf.iconsumer-ploWozeo2i4gyXoPaj2Gqg==/base.apk"],nativeLibraryDirectories=[/data/app/com.sf.iconsumer-ploWozeo2i4gyXoPaj2Gqg==/lib/arm64, /system/fake-libs64, /data/app/com.sf.iconsumer-ploWozeo2i4gyXoPaj2Gqg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]

problem occur when detecting the image, but I found the FirebaseVisionImageMetadata class on Android raw. Can't fix this problem

**Comment by jaumard** [comment]
Try with last version please :)
Closing for now feel free to re open if needed
