### ISSUE TITLE
migrate to null safty 

### ISSUE THREAD

**Issue by kw2019ltd** [santetis/flutter_camera_ml_vision#139]
Description

All dependencies are migrated to null safety. So we should migrate this package to null safety.
Resources

https://www.youtube.com/watch?v=eBr5tlumwlg&feature=youtu.be
https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730

**Comment by jaumard** [comment]
So this is blocked by this issues https://github.com/FirebaseExtended/flutterfire/issues/4625 so please go 👍🏻 so they fix their issue quickly. Until they fix this it will not work for us :( 

We can't use the fork as you can't publish on pub with git deps...

**Comment by jaumard** [comment]
Closing has 3.0.0 is null safe aware now
