### ISSUE TITLE
How to access front camera

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#14]
The default camera is the Back Camera but 
I want to access the front camera ? How can I do this. But thanks for this awesome Package.

**Comment by kevin-sakemaer** [comment]
Unfortunately It's not possible right now.
We will add it this week

**Comment by Loopex2019** [comment]
Okay thanks

**Comment by kevin-sakemaer** [comment]
we just publish 1.4.0 with this capabilities
