### ISSUE TITLE
Flutter_camera_ml_vision in ios 14 not working

### ISSUE THREAD

**Issue by ronitP12** [santetis/flutter_camera_ml_vision#143]
I have flutter project which integrated with ml_vision that works in android but on installation of pods in ios also did not give any error. the face scanner is not working in picture scanner in ios side in camera or in photo selector. any workaround or any reliable solution.

i tried all the options that are given here but no luck to find out any solution that can solve it.

**Comment by jaumard** [comment]
Yes good luck with that... 
As the models are deprecated and ml_vision didn't migrate yet to the new way of doing things it's a total nightmare... Nothing we really can do on this package. 

But feel free to jump in in the correct issue here, there is also some partial solution offered if you want to give it a shot:
https://github.com/FirebaseExtended/flutterfire/issues/4625

**Comment by ronitP12** [comment]
> Yes good luck with that...
> As the models are deprecated and ml_vision didn't migrate yet to the new way of doing things it's a total nightmare... Nothing we really can do on this package.
> 
> But feel free to jump in in the correct issue here, there is also some partial solution offered if you want to give it a shot:
> [FirebaseExtended/flutterfire#4625](https://github.com/FirebaseExtended/flutterfire/issues/4625)

Thank you for your guidance, that save my day.
