### ISSUE TITLE
Can not install version 1.4.0

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#16]
Hi Everybody. I heard about the new Feature you added about the CameraLens . But whenever i start install . There is an error which occurs to me in Puspec.yaml File. :
[looper_2019] flutter packages get
Running "flutter packages get" in looper_2019...                
Git error. Command: git rev-list --max-count=1 feature/camera_api_16_installation

fatal: ambiguous argument 'feature/camera_api_16_installation': unknown revision or path not in the working tree.

Use '--' to separate paths from revisions, like this:

'git <command> [<revision>...] -- [<file>...]'

pub get failed (69) -- attempting retry 1 in 1 second...

Git error. Command: git rev-list --max-count=1 feature/camera_api_16_installation

fatal: ambiguous argument 'feature/camera_api_16_installation': unknown revision or path not in the working tree.

Use '--' to separate paths from revisions, like this:

'git <command> [<revision>...] -- [<file>...]'

pub get failed (69) -- attempting retry 2 in 2 seconds...

Git error. Command: git rev-list --max-count=1 feature/camera_api_16_installation

fatal: ambiguous argument 'feature/camera_api_16_installation': unknown revision or path not in the working tree.

Use '--' to separate paths from revisions, like this:

'git <command> [<revision>...] -- [<file>...]'

pub get failed (69) -- attempting retry 3 in 4 seconds...

Git error. Command: git rev-list --max-count=1 feature/camera_api_16_installation

fatal: ambiguous argument 'feature/camera_api_16_installation': unknown revision or path not in the working tree.

Use '--' to separate paths from revisions, like this:

'git <command> [<revision>...] -- [<file>...]'

pub get failed (69) -- attempting retry 4 in 8 seconds...
 
Seems Like the Problem is in the camera api. But i don't know if that's true or not ?

**Comment by kevin-sakemaer** [comment]
Hi could you try to remove this folder `~/.pub-cache/git/` and then redo flutter packages get ?

**Comment by saddy001** [comment]
With the current version (flutter_camera_ml_vision: ^1.0.0), I'm getting a similar error:

> /home/saddy/flutter/bin/flutter --no-color packages upgrade
> Running "flutter packages upgrade" in test...                 
> 
> 
> Git error. Command: git fetch
> fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum Einhängepunkt /home)
> Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht gesetzt).
> 
> pub upgrade failed (69) -- attempting retry 1 in 1 second...
> Git error. Command: git fetch
> fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum Einhängepunkt /home)
> Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht gesetzt).
> 
> pub upgrade failed (69) -- attempting retry 2 in 2 seconds...

It was working fine until version 1.2.0. I already tried some suggested solutions, like exporting _GIT_DISCOVERY_ACROSS_FILESYSTEM=1_ and _git init_ but they don't solve the issue. 

I think it has something to do with the changes made to pubspec.lock in https://github.com/santetis/flutter_camera_ml_vision/pull/10/commits/d80adfa171297e4691a43734445d4e249fb9ad66

PS: _flutter clean_ doesn't change anything.

**Comment by saddy001** [comment]
Wow. I call this a fast fix.
