### ISSUE TITLE
Camera Orientation is always landscape even in portrait mode

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#20]
Whenever i the Camera start it's Preview, It is always in landscape mode even if the emulator is in 
portrait mode? Do you know any Method for solving that

![image](https://user-images.githubusercontent.com/49901727/56870720-f6db4980-6a13-11e9-9d53-45261aae233e.png)
 
As you can see it's always in landscape mode

**Comment by jaumard** [comment]
It might be just because it's the emulator :/ try check it's settings. There is nothing we can do on our side as we don't manage the video stream. It come from the camera plugin directly.
