### ISSUE TITLE
Face Detection not working (not about the Ml Package)

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#21]
Hi There. I tried Face Detection in my App but every time i try to run it , It produces an Error :
"DynamiteModule(13840): Local module descriptor class for com.google.android.gms.vision.dynamite.face not found. "
I searched  about that error and i found out that the reason for that Error is that the Storage is low. But then i checked my Storage and i had acually 1+Gb Free Storage. But still it's Showing me that Error. I know that the Error is not coming from the Camera ML Package . But can someone please help me about that , because i need it very strong.

**Comment by jaumard** [comment]
android or iOS ?

**Comment by Loopex2019** [comment]
Android

**Comment by jaumard** [comment]
Hum did you add the correct dependency ? `implementation 'com.google.firebase:firebase-ml-vision-face-model:17.0.2'` Generally I try to check the doc https://firebase.google.com/docs/ml-kit/android/detect-faces and find some differences with my setup

**Comment by Loopex2019** [comment]
No i didn't, but where can i add it

**Comment by jaumard** [comment]
It's all in the doc :) `usually `app/build.gradle`

**Comment by Loopex2019** [comment]
Okay it will try it now

**Comment by Loopex2019** [comment]
Do i need to add that Line : implementation 'com.google.firebase:firebase-ml-vision:19.0.3'
in the Build.gradle

**Comment by jaumard** [comment]
No that one come with ml package

**Comment by Loopex2019** [comment]
Okay thanks

**Comment by Loopex2019** [comment]
Thanks it works fine
