### ISSUE TITLE
Camera Ml Preview Changes (Question) 

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#22]
I just have a simple Question . I realized that the camera Preview changes by different devices. For Example by Android Emulators 
the Camera Preview is normal but it is always in landscape mode . And on a real Android Device the Camera Preview is in the normal Orientation ( So Portrait mode) but the camera is actually stretching every object its viewing. So my Question is is that only happening in Debugging mode, so when I release the app these errors will disappear or if they will not change  : What
is the Solution

**Comment by jaumard** [comment]
On real device you shouldn't see any stretching normally

**Comment by Loopex2019** [comment]
Okay but in release Mode these things will disappear Right?

**Comment by jaumard** [comment]
should already be right en debug mode, release will just improve performance

**Comment by Loopex2019** [comment]
Okay thanks
