### ISSUE TITLE
How to check if there are no faces in the Camera ?

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#23]
Hi there, I want to check if there are no faces in the Camera . I tried many ways to check that but it didn't work for me : Here is what i tried : 
 onResult: (List<Face> faces) { // i mean List of Faces
              if (faces.isEmpty) {                                                                  
                  print('Face');            
                } 
            },
// i tried faces.isEmpty
// i tried faces.length == 0   // i tried  faces.length == null      
// i tried faces == null    // i tried faces.first ==  null
 // i tried faces[0] == null

The only Thing which worked for me is the Opposite of what i want :  // faces.isNotEmpty  
Can anyone help me with that

**Comment by kevin-sakemaer** [comment]
For now you can't do that. 
The reason behind that is we do the check for you [here](https://github.com/rushio-consulting/flutter_camera_ml_vision/blob/master/lib/flutter_camera_ml_vision.dart#L251).

Maybe we can add a callback if there is no result. What do you think @jaumard ?

**Comment by jaumard** [comment]
Or just provide the empty result and let the user deal with it, because we filter only when result is a list. But for other recognition the result is not a list but it doesn't mean it's a good result so we might just forward the response imho

**Comment by kevin-sakemaer** [comment]
forwarding the response seems a good idea do we filter if the result is null ?

**Comment by jaumard** [comment]
Not sure we can as we don't know all recognizer if they have a meaning for null value or not...

**Comment by kevin-sakemaer** [comment]
@Loopex2019 you should get all the result from the firebase ml vision plugins with the 2.0.0 version.

**Comment by Loopex2019** [comment]
So know I can check if there are no faces Right  ? And do I check it in the onResult?

**Comment by jaumard** [comment]
Now isEmpty will work in `onResult `

**Comment by Loopex2019** [comment]
Okay thanks for your support
