### ISSUE TITLE
Error while Launching the camera Preview

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#28]
Hi there the after i made the new update of version 2.0.0 , i checked if there are no faces and it worked for me but the problem is that whenever i start launching the Camera Preview it shows me
 the following Error:

`I/flutter (18912): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (18912): The following assertion was thrown building CameraMlVision<List<Face>>(dirty, state:
I/flutter (18912): CameraMlVisionState<List<Face>>#67fec):
I/flutter (18912): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1655 pos 14:
I/flutter (18912): '!children.any((Widget child) => child == null)': is not true.
I/flutter (18912):
I/flutter (18912): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18912): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18912): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18912):   https://github.com/flutter/flutter/issues/new?template=BUG.md`

So i tried to reopen  Visual Studio Code and i still got the same error.

**Comment by kevin-sakemaer** [comment]
Could you share your code with us ?

**Comment by Loopex2019** [comment]
Okay one Minute

**Comment by Loopex2019** [comment]
`import 'package:flutter/material.dart';

import 'package:flutter_camera_ml_vision/flutter_camera_ml_vision.dart';

import '../Navigation/my_navigator.dart';

import '../painting/FacePainter.dart';

import 'package:firebase_ml_vision/firebase_ml_vision.dart';

import '../values/screen_values.dart';



import 'package:gradient_widgets/gradient_widgets.dart';

import 'package:camera/camera.dart';

class FaceDetectionCamera extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _FaceDetetctionCameraState();
}

class _FaceDetetctionCameraState extends State with TickerProviderStateMixin {
 
  bool _animationDone = false;
  AnimationController _controller;
  AnimationController _controller2;
  Animation<double> _radius;
  Animation<double> _radius2;
  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      vsync: this,
      duration: Duration(seconds: 5),
    );
    _radius = Tween(begin: 0.0, end: 1.0).animate(CurvedAnimation(
      parent: _controller,
      curve: Curves.fastOutSlowIn,
    ));
    _controller2 = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 1500),
    );
    _radius2 = Tween(begin: 0.85, end: 1.0).animate(CurvedAnimation(
      parent: _controller2,
      curve: Curves.bounceInOut,
    ));
    _controller.forward().then((_) {
      _animationDone = true;
    });
  }

  Widget _callAlertDialog() {
    return AlertDialog(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(22.5),
      ),
      title: Text(
        'Something went wrong',
        style: TextStyle(color: Colors.red),
      ),
      content: Column(
        children: [
          Text('There was an Error while launching the Camera.'),
          SizedBox(
            height: Screen.getHeight(10.5),
          ),
          Text('Please try Again'),
        ],
      ),
      actions: <Widget>[
        FlatButton(
          child: Text('OK'),
          onPressed: () {
            Navigator.pop(context);
            MyNavigator.goToSignUpPage2(context);
          },
        ),
      ],
    );
  }

  Widget _buildNoFaceText() {
    return Row(
      children: [
        SizedBox(
          width: Screen.getWidth(220.0),
        ),
        Align(
          alignment: Alignment.center,
          child: Row(
            children: <Widget>[
              Text(
                'Need to find your Face',
                style: TextStyle(
                  fontSize: Screen.getFont(55.5),
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1.5,
                  color: Colors.red[900],
                ),
              ),
              SizedBox(
                width: 4.5,
              ),
              Icon(
                Icons.face,
                color: Colors.black,
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildManyFacesText() {
    return Row(
      children: [
        SizedBox(
          width: Screen.getWidth(220.0),
        ),
        Align(
          alignment: Alignment.center,
          child: Text(
            'Need to find only 1 Face',
            style: TextStyle(
              fontSize: Screen.getFont(55.5),
              fontWeight: FontWeight.bold,
              color: Colors.red[900],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildDetectButtonAndTabText() {
    return Stack(
      children: [
        Positioned(
          top: 360,
          left: 138,
          child: ScaleTransition(
            scale: _animationDone == true ? _radius2 : _radius,
            child: InkWell(
              onTap: () {
                setState(() {
                  _controller2.forward();
                });
              },
              child: Container(
                padding: EdgeInsets.all(1.8),
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  gradient: Gradients.cosmicFusion,
                ),
                child: Container(
                  padding: EdgeInsets.all(15.0),
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    color: Colors.black,
                    //     gradient: Gradients.deepSpace,
                  ),
                  child: CircleAvatar(
                    backgroundColor: Colors.black,
                    radius: 25,
                    backgroundImage: AssetImage(
                      'assets/face-detection-line-icon 2.png',
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
        Positioned(
          bottom: 10,
          left: 100,
          child: Text(
            'Tab Here to detect your Face',
            style: TextStyle(
              color: Colors.grey[700],
              fontSize: 15.0,
            ),
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    final double _deviceWidth = MediaQuery.of(context).size.width;
    final double _deviceHeight = MediaQuery.of(context).size.height;
    bool _noface = false;
    bool _manyfaces = false;
    Screen.checkScreen(context);
    return Scaffold(
      body: SafeArea(
        child: SizedBox(
          width: _deviceWidth,
          height: _deviceHeight,
          child: CameraMlVision(
            loadingBuilder: (BuildContext context) {
              return Center(
                child: CircularProgressIndicator(
                  strokeWidth: 2.0,
                  valueColor: AlwaysStoppedAnimation(Colors.black87),
                ),
              );
            },
            cameraLensDirection: CameraLensDirection.front,
            detector: FirebaseVision.instance
                .faceDetector(FaceDetectorOptions(
                  enableLandmarks: true,
                  enableClassification: true,
                ))
                .processImage,
            errorBuilder: (BuildContext context, CameraError error) {
              return _callAlertDialog();
            },
            onResult: (List<Face> faces) {
              if (faces.isEmpty) {
              _noface = true;
              print('No Face');
              } else if (faces.length > 1) {
                _manyfaces = true;
              }
              return CustomPaint(
                painter: FacePainter(faces: faces),
              );  
            },
            overlayBuilder: (BuildContext context) {
              if (_noface == !_noface) {
                _buildNoFaceText();
              } else if (_manyfaces == !_manyfaces) {
                _buildManyFacesText();
              }
              _buildDetectButtonAndTabText();
            },
          ),
        ),
      ),
    );
  }
}
`

**Comment by Loopex2019** [comment]
Oh I am really sorry . I just forgot to add  the return statement!
