### ISSUE TITLE
How to return a Widget if there are no faces (Question)

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#30]
Hi. Checking if there is no face is working great but with printing some Text to the Debug Console.
But i want to return a Widget. Can i do this in the `onResult` ? i tried but it didn't work for me. So 
i tried display a Widget in the `overlayBuilder` by initializing a  boolean value and set it to false
: ` onResult: (List<Face> faces) {
              if (faces.isEmpty) {
                _noface = true;
                   print('No Face');
              } 
            },
            overlayBuilder: (BuildContext context) {
              if (_noface ==  true) {
                return _buildNoFaceText();
              } 
              return _buildDetectButtonAndTabText();
            },`    
I initialized the boolean value on the top of the class and it's default is `false`.
My Goal is to connect the Checking of the `onResult` with the `overlayBuilder` to render 
the Widget i want.  Is there something wrong in my Logic Code and if there can someone tell me the Solution ?

**Comment by kevin-sakemaer** [comment]
in onResult you should use `setState` to update your widget

**Comment by Loopex2019** [comment]
Thanks for your Help.

**Comment by Loopex2019** [comment]
Sorry but i have another Question: How to add a CustomPainter to paint something around a Face in the 
`onResult`. I mean i had already created my own Custom Painter with the detected face size , but i just don't 
know how to implement it in `onResult`.

**Comment by bwnyasse** [comment]
Hello @Loopex2019 ,

After reading your last comment , I would suggest you to contact the [support ](https://rushio-consulting.fr/support/) in this case. 
Today rushio-consulting provide support to help you develop extra features not covered by their open source projects. 

Bests regards.

**Comment by Loopex2019** [comment]
So I will re-ask the Question about the Custompainter in the Support?

**Comment by bwnyasse** [comment]
Hi @Loopex2019 

Allow me to clarify that the support for additional development is **not free**. 

For sure you can ask the question about the **custompainter** in the support.

For now , you can clearly explain your requirements to the support. And I Guess if it IS something the team Can covered, they will send you an invoice.

Thk U.

**Comment by Loopex2019** [comment]
Okay thanks for your advice
