### ISSUE TITLE
Support for taking a photo

### ISSUE THREAD

**Issue by ghost** [santetis/flutter_camera_ml_vision#34]
Currently you handle taking pictures, however, these are hidden in private methods. Would it be possible to make a public method for taking a photo and accessing that file?

**Comment by kevin-sakemaer** [comment]
You want to take a picture when you detect something with ml_vision ?

**Comment by kevin-sakemaer** [comment]
You now have this functionality in 2.1.0 available on [pub](https://pub.dev/packages/flutter_camera_ml_vision) :)
