### ISSUE TITLE
Build exception after upgrade to release v2.1

### ISSUE THREAD

**Issue by lewixlabs** [santetis/flutter_camera_ml_vision#38]
Hi,
after I did a "flutter package upgrade" i get this exception on build:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'META-INF/androidx.exifinterface_exifinterface.version'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************

Gradle task assembleDebug failed with exit code 1
```

![image](https://user-images.githubusercontent.com/7371215/57934702-8dd34d00-78c0-11e9-8aee-1efbcb344736.png)

I confirm doing rollback (by git) exception doesn't happen.
From these logs, issue seems related to androidX migration on plugins (camera, firebase_mlkit, etc) your package depends on.
I use only to your package in pubspec.yaml.

Could you help me?
Have I migrate to androidX following this guide? https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
Maybe I did something wrong.

Thanks guys, if you need more infos let me know
Lewix

**Comment by kevin-sakemaer** [comment]
Does the example work on your machine ? If yes please compare our android folder with your.

If there is no difference could you share a repos with a non working example inside ?

**Comment by lewixlabs** [comment]
Hi @Kleak ,
I meticulously followed official guide to manually migrate to AndroidX
_"Not recommended: Manually migrate your app"_
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
and further change I did is updating, in build.gradle (android level)
`ext.kotlin_version = '1.2.71' `to `ext.kotlin_version = '1.3.0' `inside buildscript
and now I get no issues.

Maybe my issue is related to kotlin version only, but I hope this info could be usefull to other eventually encounter this issue.
Feel free to close this issue, thank you!

Lewix

**Comment by kevin-sakemaer** [comment]
It's probably related to kotlin.

We are not using it in the package and it's not used in the camera plugin or the firebase_ml_vision plugins.
