### ISSUE TITLE
Optionally don't request microphone permission

### ISSUE THREAD

**Issue by saddy001** [santetis/flutter_camera_ml_vision#43]
It would be nice to not ask the user for microphone permission if it is not needed, e.g. when just using some OCR. 

I think it could be implemented as an additional parameter or dependent on the given detector. 
Accoring to https://github.com/flutter/flutter/issues/31477#issuecomment-498403813 there is a parameter "enableAudio" to CameraController.

**Comment by kevin-sakemaer** [comment]
I think we don't need the audio at all.
Will do it as soon as i have some free time :+1:

**Comment by saddy001** [comment]
Great, thank you.
