### ISSUE TITLE
Can not install version 2.2.0 cause of the firebase ml package.

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#48]
I tried installing the latest version of the Package but whenever i run it , it always show me that Error : [looper_2019] flutter packages get
Running "flutter packages get" in looper_2019...                
Because flutter_camera_ml_vision >=2.1.0 depends on firebase_ml_vision ^0.8.0 and looper_2019 depends on firebase_ml_vision ^0.7.0, flutter_camera_ml_vision >=2.1.0 is forbidden.

So, because looper_2019 depends on flutter_camera_ml_vision ^2.2.0, version solving failed.
pub get failed (1)
exit code 1
I think it has something to do with the firebase ml vision package version 0.7.0

**Comment by kevin-sakemaer** [comment]
Could you share your pubspec ?

**Comment by Loopex2019** [comment]
Here is my Pubspec file :

name: looper_2019
description: A new Flutter project.



# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  gradient_widgets: ^0.4.1
  firebase_ml_vision: ^0.7.0
  firebase_face_contour: ^0.1.0
  flutter_camera_ml_vision: ^2.2.0
  simple_animations: ^1.3.0
  flutter_screenutil: ^0.5.2
  scoped_model: ^1.0.1
  cloud_firestore: ^0.11.0+2
  flare_flutter: ^1.5.1
  
 
dependency_overrides:
  camera: 
    git:
      url: https://github.com/jaumard/plugins.git
      ref: feature/camera_api_16_installation
      path: packages/camera   

           
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/LOOPER2019 (4) (1).png
   - assets/imagine.jpg
   - assets/background-2734972_1280 (2).jpg
   - assets/face-detection-line-icon 2.png
   - assets/face-detection2.png
   - assets/new similarties.jpg
   - assets/add.png
   - assets/camera.png
   - assets/clapperboard.png
   - assets/new2.jpg
   - assets/hi.jpg
   - assets/face24.jpg
   - assets/Image.jpg
   - assets/freeze Mode.webp
   - assets/timer1.jpg
   - assets/timer2.jpg
   - assets/women profile.jpg
   - assets/right-arrow.png
   - assets/mars.png
   - assets/male taste.png
   - assets/female.png
   - assets/female taste.png
   - assets/New File 5 (2).flr
   - assets/verification.png
   - assets/cancel-mark.png
   - assets/user.png
   - assets/male-user.png
   - assets/Profile Picture Male.png
   - assets/yep.png
   - assets/check (1).png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/quicksand-bold.ttf
        - asset: fonts/quicksand-bold.ttf
  #         style: italic
    - family: Magistral
      fonts:
         - asset: fonts/FontsFree-Net-Magistral3.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

**Comment by Loopex2019** [comment]
This is the Dependencies part : 
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  gradient_widgets: ^0.4.1
  firebase_ml_vision: ^0.7.0
  firebase_face_contour: ^0.1.0
  flutter_camera_ml_vision: ^2.2.0
  simple_animations: ^1.3.0
  flutter_screenutil: ^0.5.2
  scoped_model: ^1.0.1
  cloud_firestore: ^0.11.0+2
  flare_flutter: ^1.5.1
  
 
dependency_overrides:
  camera: 
    git:
      url: https://github.com/jaumard/plugins.git
      ref: feature/camera_api_16_installation
      path: packages/camera

**Comment by kevin-sakemaer** [comment]
please remove firebase_ml_vision and the dependency_overrides. It should work after that.

**Comment by jaumard** [comment]
dependency_overrides of camera is not needed anymore, 
and firebase_ml_vision is not needed if you don't use it on your code

**Comment by Loopex2019** [comment]
I can not remove  the firebase ml package because I am using in other things Like getting the face landmarks and other things too

**Comment by kevin-sakemaer** [comment]
if you can't, use `firebase_ml_vision: ^0.8.0` in that case

**Comment by Loopex2019** [comment]
Thanks it worked for me
