### ISSUE TITLE
Getting the CameraImage

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#49]
Hi is there a way that we can get the CameraImage of the Camera Stream and do some Customization with it ?

**Comment by kevin-sakemaer** [comment]
You want to modify the CameraImage before showing it in the preview ?

**Comment by Loopex2019** [comment]
No i mean like adding Filters to the CameraImage

**Comment by Loopex2019** [comment]
Okay now i figured out how to do Customization on the Camera without using CameraImage
