### ISSUE TITLE
MLKit Text Recognition support

### ISSUE THREAD

**Issue by lewixlabs** [santetis/flutter_camera_ml_vision#5]
Hi,
first congrats! Great mlkit & Camera plugin, it works better (for me) than original from flutter team 👍
My question is: does your flutter plugin support text detection feature too?
I can't find an example.

Thanks!

**Comment by jaumard** [comment]
Hi :) 
Sure it does ! it normally support all the detection that ml vision support ! We only show barcode example as it's the one we need right now :) 

to do text detection just try something like: 

```
CameraMlVision<VisionText>(
            detector: FirebaseVision.instance.textRecognizer().processImage,
            onResult: (VisionText barcodes) {

            },
          )
```
we didn't try but normally should work ^^

**Comment by lewixlabs** [comment]
Urca (Italian exclamation :) )! This is was I was trying to do, but i stopped being in doubt.
I'll give it a try!
Thanks!

I'll let you know

**Comment by lewixlabs** [comment]
Works!
Just a weird case, but happens with official firebase plugin too:
scanning my highlighter Promarker on other old device in my office, hisense pureshot l671, "Promarker" text on the pen is recognized as

> I/flutter (13712): AEAAMONg
> D/skia    (13712): onFlyCompress
> I/flutter (13712): ******** visionText => **oaaiAMANnUA**
> I/flutter (13712): SEAAMo1g
> D/skia    (13712): onFlyCompress
> I/flutter (13712): ******** visionText => **oaaiAMAaUA**
> I/flutter (13712): AENSAMO1g
> D/skia    (13712): onFlyCompress
> I/flutter (13712): ******** visionText => **oaaiAMANanGA**
> I/flutter (13712): gENgAMOg
> D/skia    (13712): onFlyCompress
> I/flutter (13712): ******** visionText => **oJi1AMA3nUA**
> I/flutter (13712): AEAMo1g
> D/skia    (13712): onFlyCompress
> I/flutter (13712): ******** visionText => **oJ1AMAN3VmUA**

Happening this issue on both plugins (yours and official firebase flutter plugin) seems mlkit native library doesn't correctly handle rotation device info, or returns Vision Text result with inverted bytes?

Anyway with your plugin flutter code is cleaner, because it handles camera and mlkit at the same time.
Thanks!

**Comment by jaumard** [comment]
Glad it worked ! :) yeah we can't do better if the problem is native side, try to open an issue on Flutter with your cases for the ml vision guys to look at it :)

**Comment by lewixlabs** [comment]
I noticed in your source code plugin you use official camera plugin (& camera stream code inspired by https://github.com/bparrishMines/mlkit_demo, to retrieve camera stream).
Maybe the issue is related to camera plugin.

P.S.: sorry I was writing this post while you were closing this issue.

Hi!
Lewix

**Comment by jaumard** [comment]
Yes we're using a mix between camera, firebase_ml_vision and inspired by mlkit_demo ^^ 
There is an open issue on the flutter repo saying that there might be some issues with rotations as flutter doesn't offer a way to retrieve it, so yes that might be the issue here https://github.com/flutter/flutter/issues/19274
