### ISSUE TITLE
Cloned repo, opened in Android Studio - gradle errors

### ISSUE THREAD

**Issue by nhwilly** [santetis/flutter_camera_ml_vision#51]
![2019-06-17_16h52_27](https://user-images.githubusercontent.com/7560842/59635956-64f0e280-9120-11e9-8719-f103256d42c1.png)

I'm not sure what's happening.  I was having all kinds of problems in VSCode and adapting to my own project, so I punted and went back to the repo/example.

Then I punted again and switched to Android Studio and get even more errors.

I created a new project and moved the example `main.dart` into it and got it to work, sort of.  Never got a recognized bar code, but at least it ran.  Errors like this:
`
D/libGLESv2(32723): STS_GLApi : DTS, ODTC are not allowed for Package : com.example.tco_camera
`
happened on launch.

Then when I ran it, I got this:
```
E/MethodChannel#plugins.flutter.io/firebase_ml_vision(32723): java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.tco_camera. Make sure to call FirebaseApp.initializeApp(Context) first.
```
and the device screen freezes.

Things didn't lock up when I ran the same project on Android Studio, but I got the same error.

I'n going to let it rest for a week or two while I work on something else.  HTH

**Comment by kevin-sakemaer** [comment]
Hey @nhwilly,
did you setup firebase  ?

**Comment by zura35** [comment]
Hi! I have come across the same problem as well. I have followed the instructions on Firebase to set up the application (adding google-services.json etc). However, the following still exists when I run `flutter build apk` in example:
```
Initializing gradle...                                              0.7s
Resolving dependencies...                                          11.6s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      10.9s
Gradle task assembleRelease failed with exit code 1
```

My `flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.4)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Although I am able to build my app with the use of this library. :thinking: 
-----
Updates:
It turned out that I have misplaced the google-services.json file. It should be placed underneath /android/app instead of /android.

Now it's working!

**Comment by nhwilly** [comment]
I'll try that.

There are only about 100 places with the same build/gradle file names. 

Easy to get mixed up.

Thanks!
