### ISSUE TITLE
Is it possible to take video recordings and activate the ml vision plugin at the same time?

### ISSUE THREAD

**Issue by ysrarff** [santetis/flutter_camera_ml_vision#58]
Hi there,

Sorry again for spamming on the issue page but I just wanna know if it's possible to change the isStreaming() function to startVideoRecording() while accessing the ML detector parameters? 

If possible, could you provide an example? Thank you! 

P/S: awesome package btw

**Comment by kevin-sakemaer** [comment]
Hi,

You already have access to the `startVideoRecording` method from the `CameraMlVisionState` class.

You will just need to pass a Key to `CameraMlVision` and then acces the state from the key.

Creating the Key :
```
final _scanKey = GlobalKey<CameraMlVisionState>();
```

Passing the Key to CameraMlVision :
```
CameraMlVision<List<Face>>(
  key: _scanKey,
  // other params
```

starting the video recording : 
```
await _scanKey.currentState.prepareForVideoRecording();
await _scanKey.currentState.startVideoRecording('path/to/your/file');
```

Hope all this help you.

**Comment by ysrarff** [comment]
Hi @Kleak, thanks for the reply.

I apologize if I didn't make myself clear due to the generic inquiry.

Currently, I am able to record videos using the GlobalKey or using it to initialize an image stream (ML). But not both at the same time, since the .startVideoRecording() only allows a String path argument. 

Whenever, I try to call .startVideoRecording(), it cancels out the .startImageStream(). So I would like to know if it is possible to pass in a ML detector inside .startVideoRecording() or is there a way to asynchronously activate both the .startVideoRecording() and .startImageStream() at the same time. Thanks a bunch!

**Comment by kevin-sakemaer** [comment]
Hi could you test with [this](https://github.com/rushio-consulting/flutter_camera_ml_vision/tree/fix-recording-video) branch ?
