### ISSUE TITLE
Switching between CameraLensDirections 

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#59]
Hi . I recently want to add a Button to change the CameraMLVision View on the back lens and the other is on the front one . So i created an IconButton for doing this Task. When you click the button it rotates itself meaning that the lens Direction is now switched to the front , The default is the back.
So the Rotation Part worked fine for me . For the Real Switching Part between the two Lens Directions , i added a boolean variable . i named `_switchCamera` . Now when the Rotation Animation finishes i set this boolean variable to `true` and when the user clicks it again it will be set to `false` :   
` onPressed: () {
      setState(() 
    _animationController.forward().then((_) 
         _switchCamera = true;
            });
            });
        if (_animationController.isCompleted) {
            _animationController.reverse().then((_) {
              _switchCamera = false;
            });
          }
        },` 

Till now that's fine . Now when i check this inside The `cameraLensDirection` Argument , it doesn't work  :  
 `cameraLensDirection: _switchCamera == true
            ? CameraLensDirection.front
            : CameraLensDirection.back,`

**Comment by Loopex2019** [comment]
Any One can help ?

**Comment by kevin-sakemaer** [comment]
Could you try to change the key properties of the widget ?
something like Key('front') / Key('back') when you switch the direction

**Comment by Loopex2019** [comment]
Sorry but can you give an example of that

**Comment by Loopex2019** [comment]
Hi i solve it  by calling _controller.initialize() again
