### ISSUE TITLE
Camera error

### ISSUE THREAD

**Issue by hirotomobtc** [santetis/flutter_camera_ml_vision#6]
Hi, thank you for the plugin. I'm trying to run the example to read a barcode but I'm facing the error below:
MissingPluginException (MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera))

Can you help me please? Thanks!
![image](https://user-images.githubusercontent.com/49536052/55990124-e6397e00-5c74-11e9-8591-17062bb6e636.png)

**Comment by kevin-sakemaer** [comment]
Hi
Did you did `flutter packages get` in the example folder before launching the example ?
could you share the version of the device this happen ?
also the version of the os you are running on ?

**Comment by kevin-sakemaer** [comment]
we have find the problem and will make a fix soon.
will keep you informed

**Comment by hirotomobtc** [comment]
Thanks! it's working fine!
