### ISSUE TITLE
How can I use takePicture after a Barcode was detected?

### ISSUE THREAD

**Issue by drosrel** [santetis/flutter_camera_ml_vision#60]
I'm trying to use the last image taken before the Barcode detection. The App closes after this code:
```dart
  final _scanKey = GlobalKey<CameraMlVisionState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SizedBox(
          width: MediaQuery.of(context).size.width,
          child: new CameraMlVision<List<Barcode>>(
            key: _scanKey,
            detector: FirebaseVision.instance.barcodeDetector().detectInImage,
            overlayBuilder: (c) {
              String _imageName;
              _scanKey.currentState.takePicture(_imageName);
              print(_imageName);
              return Container(
                decoration: ShapeDecoration(
                  shape: _ScannerOverlayShape(
                   borderColor: Theme.of(context).primaryColor,
                    borderWidth: 3.0,
                  ),
                ),
              );
            },
```

**Comment by drosrel** [comment]
I've found a solution in the examples from firebase_ml_vision.

Thanks

**Comment by 948911908** [comment]
hello，I have the same problem. How did you solve it?

**Comment by nirbar89** [comment]
hi,

have fun:

`final _scanKey = GlobalKey<CameraMlVisionState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SizedBox(
          width: MediaQuery.of(context).size.width,
          child: CameraMlVision<List<Barcode>>(
            key: _scanKey,
            overlayBuilder: (c) {
              return Container(
                decoration: ShapeDecoration(
                  shape: _ScannerOverlayShape(
                    borderColor: Colors.amber,
                    borderWidth: 3.0,
                  ),
                ),
              );
            },
            detector: detector.detectInImage,
            onResult: (List<Barcode> barcodes) async {
              if (!mounted ||
                  resultSent ||
                  barcodes == null ||
                  barcodes.isEmpty) {
                return;
              }
              resultSent = true;
              try {
                // Ensure that the camera is initialized.
                // Construct the path where the image should be saved using the path
                // package.
                final path = join((await getTemporaryDirectory()).path,
                        '${DateTime.now()}.jpg')
                    .replaceAll(' ', '-')
                    .replaceAll(':', '');
                // Attempt to take a picture and log where it's been saved.
                await _scanKey.currentState.takePicture(path);
                print('*********');
                print(path);
                print('*********');
              } catch (e) {
                // If an error occurs, log the error to the console.
                print(e);
              }
              Navigator.of(context).pop<Barcode>(barcodes.first);
            },
            onDispose: () {
              detector.close();
            },
          ),
        ),
      ),
    );
  }
}`
