### ISSUE TITLE
CameraPreview is pixelated 

### ISSUE THREAD

**Issue by Loopex2019** [santetis/flutter_camera_ml_vision#61]
The Camera Preview is always pixelated like that : 
![Screenshot_20190701-083312_Gallery](https://user-images.githubusercontent.com/49901727/60415377-463c2280-9bdb-11e9-9f44-0fe765b79523.jpg)
Compared to the WhatsApp Camera which is like that : 
![Screenshot_20190701-083204_WhatsApp](https://user-images.githubusercontent.com/49901727/60415444-75529400-9bdb-11e9-93c0-f8fce9ee5f41.jpg)
Does this have something with the ResolutionPreset in my case it's a medium 
Resolution .

**Comment by jaumard** [comment]
Yes try high :)

**Comment by Loopex2019** [comment]
Okay but for my information high does not work on ios

**Comment by jaumard** [comment]
If it doesn't work there is nothing we can do, open an issue on the `camera` plugin directly, but high should definitely work or it's a big bug on the camera plugin

**Comment by Loopex2019** [comment]
Okay thanks it worked for me on Android . Will try with IOS later
