### ISSUE TITLE
Error while initializing camera

### ISSUE THREAD

**Issue by nikitattt** [santetis/flutter_camera_ml_vision#68]
Just tried to reproduce the example on Android. Made all steps with firebase, gradle and AndroidManifest. Launched without errors, but when clicking "Scan product" get error message `_CameraState.error CameraError.cantInitializeCamera`. 
  Looked for your source code. As I got it may be a problem that my phone doesn't allow to make a camera source. I have Android 9.0 Pie. Maybe because of no Permission request?

**Comment by jaumard** [comment]
Permission should be asked by the camera plugin, we don't manage permissions at all on our side. This error can be throw when another program already have access to the camera or if there any problem with the init of the camera, but shouldn't be for permission problem

**Comment by jaumard** [comment]
Closing this as nothing can be done on our side
