### ISSUE TITLE
Access camera controller

### ISSUE THREAD

**Issue by tamdesktop** [santetis/flutter_camera_ml_vision#75]
We can detect faces from the camera. It's better if I can access camera controller to take photo, or return image in onResult callback.

Thanks,

**Comment by kevin-sakemaer** [comment]
We already provide access to the takePicture and friends function.
https://github.com/rushio-consulting/flutter_camera_ml_vision/blob/master/lib/flutter_camera_ml_vision.dart#L144

**Comment by tamdesktop** [comment]
Sorry for missing that
