### ISSUE TITLE
Add the possibility to have a custom overlay

### ISSUE THREAD

**Issue by kevin-sakemaer** [santetis/flutter_camera_ml_vision#8]

**Comment by lewixlabs** [comment]
Agree, I'm using CameraMlVision inside a showModalBottomSheet method, but it seems capturing camera stream bytes from the whole available area, right?

**Comment by jaumard** [comment]
Yes that's right, and we don't place to change this on this issue. It can be nice to still have an overlay if you want to position other widget where you detect stuff, or just to make a barcode skin (even if the all area is taking into account)
