### ISSUE TITLE
multiple qrcode track

### ISSUE THREAD

**Issue by nicolalopatriello** [santetis/flutter_camera_ml_vision#83]
Hi, is possibile to track multiple qrcode? (Similar to attached image)
If not, which is the correct way to do this?

Thanks.

![Screenshot from 2019-10-29 12-01-12](https://user-images.githubusercontent.com/3687153/67761622-f283fd80-fa43-11e9-9e59-2d1640f22e6b.png)

**Comment by jaumard** [comment]
Yes you can :) you receive all the found qrcode on the image so you can do whatever you want with those info.
