### ISSUE TITLE
Barcode scanner only reads vertical barcodes

### ISSUE THREAD

**Issue by mikuhl-dev** [santetis/flutter_camera_ml_vision#88]
With the phone in portrait mode, the barcode scanner only reads the barcode when its vertical (rotating the barcode 90 degrees), while the barcode is horizontal (the usual position) it does not read.
![barcode](https://user-images.githubusercontent.com/5238952/68916292-517b8f00-0733-11ea-8ac1-785de5339f7d.png)

**Comment by jaumard** [comment]
On both iOS and Android ?

**Comment by kevin-sakemaer** [comment]
could you try to change the resolution to something like `ResolutionPreset.high` ?

**Comment by jaumard** [comment]
@Kleak I manage to reproduce, barcode are not recognize (or only vertically) when using low but work again when using high

**Comment by kevin-sakemaer** [comment]
ok we will default to high and not low. Will make a PR tomorrow

**Comment by jaumard** [comment]
@Kleak reminder :)
