### ISSUE TITLE
camera choppy on iPhone 6

### ISSUE THREAD

**Issue by jaddoescad** [santetis/flutter_camera_ml_vision#91]
i set the resolution on medium, and the camera is very choppy on iPhone 6 but doing well on iPhone 7.

When i set it on low, it works on iPhone 6 aswell. Is it normal that it would be this choppy on medium resolution? What kind of mechanism is causing it to be this heavy? I tried opening the regular camera for iPhone 6, and it wasn’t choppy at all with good resolution.

I also have no code inside my completion handler just a print statement.
 ______________________________________________________________________________________

testing on iphone 6 and iphone 5s and same issue occurs, but works perfectly on older models

**Comment by jaumard** [comment]
We're using the official camera plugin so performance issue will have to go there, it might also be because some computation are done in dart. We have an issue open to move those computation into an isolate (#85) but not sure it will change anything until it's done
