### ISSUE TITLE
calling setState from onResult crash the app

### ISSUE THREAD

**Issue by eliaweiss** [santetis/flutter_camera_ml_vision#92]
CameraMlVision<VisionText>(
                      overlayBuilder: zPaint,
                      detector:
                          FirebaseVision.instance.textRecognizer().processImage,
                      onResult: (VisionText vt) {
                        if (!mounted) {
                          return;
                        }
                        print("> " + vt.text.toString());
                        if (vt.text.length > 0) {
                          setState(() {t++;
                          });
                        }
                      },

What I want is to change the overlayBuilder, therefore I want to call setState to make the widget paint it self.

Is there another way to do it?

**Comment by jaumard** [comment]
what's the error exactly ?

**Comment by jaumard** [comment]
you can try wrapping setState with `scheduleMicroTask` see if it's better

**Comment by eliaweiss** [comment]
It was solved with an upgrade
