### ISSUE TITLE
flash/torch does not work

### ISSUE THREAD

**Issue by MarcelEdward** [santetis/flutter_camera_ml_vision#95]
When I try to use a torch when the camera_ml_vision is scanning then I get an error:

Torch Failed : CAMERA_IN_USE (4): setTorchMode:1914: Torch for camera "0" is not available due to an existing camera user

I need the flash/torch functionality cause sometimes we want scan something in the shadow

**Comment by jaumard** [comment]
We're not dealing with the camera, we're just using the official camera plugin, so you should open an issue for it there. Because we can't do anything in this plugin for it ^^
